# 2.0
    sentences = [
        "that's all right",
        "televisions are expensive these days",
        "the colonial porte cochre sets the tone for Waikiki's most charming historic hotel, which opened in 1901",
        "and you just sift",
        "you think there's somethin' in all that talk Topham was givin' lip to? Anse asked",
        "are the uh Oldsmobiles that you're looking at are they the demos or they used are they new",
        "and she's doing it i mean it's not like it's like",
        "ancient and ill-maintained, it starts off shiny and gets rapidly creakier as it approaches the border",
        "one of the first impressions you'll get at the airport in Delhi or Mumbai (Bombay) is the diversity of ethnic types",
        "what about people from uh Pennsylvania what do they think about Texans",
        "b. A lottery ticket that gives you a 10/11 chance of winning $5 million",
        "one is that--contrary to the opinion of virtually everyone else in the world--AIDS in fact hasn't reduced gay males' life expectancy by that much--a few years, at most",
        "he went on and talked about this and that but at dinner repeated exactly the same instructions--I was to run for President, announce the third week in April, etc",
        "'Of course,' Greuze said quickly, 'I wasn't at all implying-'",
        "who better to help a candidate extract weighty lessons from his personal history, to teach him to tell voters that their own successes depend on his own?",
        "mademoiselle Cynthia.",
        "by time-shifting this feel-good scene forward, Man on the Moon relieves the true story of Kaufman's depressing decline",
        "the coast road takes you west to Pointe du Grouin, a cliff 40 m (130 ft) high, with a spectacular view of the Chausey Islands to the north and to Saint-Malo, a town steeped in seafaring history; its sailors left their name as far afield as the Malouines, claimed by the British as the Falkland Islands",
        "i fully appreciate that much work may be needed before agencies' respective performance management systems are able to support a more direct link between pay and individual knowledge, skills, and performance",
        "a profile of Steve Jurvetson, the 33-year-old venture capitalist who seeds Internet startups, predicts he will prosper even though Internet IPOs no longer promise exponential returns"
    ]

# 2.1
    sentences = [
        "Halfway along the narrow peninsula you'll find Sangster International Airport, the main airport of entry for Kingston and the eastern part of the island.",
        "Because traditional work schedules influence internal control in T&amp;A systems, this document contains two major parts, the first dealing with civilian employees who are expected to be working, usually during certain times and the second part dealing with members of the active duty armed services who are expected to be in a duty status and thus on call 24 hours a day.",
        "But an unfortunate side effect is the lost opportunity to provide some socially desirable planned obsolescence.",
        "An article marvels at the revival of religion in China, now used by the Communist Party to control a restive population.",
        "This is shown in the supply curve in Figure 9.",
        "Rudy plans to consolidate his lead in the burbs by pushing school vouchers, while Hillary will tap into health-care frustrations and make the election a national contest.",
        "yeah what do they do",
        "the drug can use you",
        "How may a proper person handle the delicate matter of bad breath when happenstance forces one into consulting with someone on the boss' staff?",
        "uh-huh uh-huh uh-huh i know my brother had trouble with fire ants and that even uh yeah and they be can be a real dickens",
        "The Royal Dining Room is situated at the top of the Great Stair.",
        "HCFA received 409 comments in the response to the notice.",
        "but there's always a sell",
        "so it's a little bit something we try doing and there's there's a lot of good children's programs that you could watch they could watch several hours every day",
        "And that's the great thing, isn't it? ",
        "Never did a piece of architecture more exactly express the personality of its builder than the Ceteau de Versailles ' extravagant, pompous, dazzling, formidable, glorious, and vain.",
        "oh God  No why don't you go first",
        "Without credibility, the CIO organization will struggle to be accepted as a full participant in the development of new organizational systems and processes.",
        "Some 80 km (50 miles) up the autoroute du Nord from Paris, Com?­piygne is another classical Ile-de-France royal hunting forest and palace.",
        "you you have exceeded your ten minutes time limit hang up within the next thirty seconds so",
    ]

# 2.2
    sentences = [
        "Probably the most important reform was the least  the decentralization that increased regional autonomy and reversed the age-old trend of concentrating political, economic, and administrative power in the national capital.",
        "They saw their lives lost in that burning town.",
        "During the program's critical design review, about 56 percent of the drawings were completed and, while the program did not meet the best practice of 90 percent complete, it did have additional drawing data of the F/A-18 E/F assemblies available for review at the critical design review.",
        " The music is played on typically Catalonian and in some cases uniquely Ibicencan  a wooden flute and a small drum (handled simultaneously by a single ambidextrous man), a sort of steel sabre struck in rhythm, and large castanets.",
        "What is important is that labor negotiations take place within the framework of a situation where the loss of business to competitors is an everyday reality.",
        "Well, he showed them.",
        "yeah yeah if you like Platoon yeah if you liked Platoon you'll probably really like this because it takes pretty much the same direction for the time you know uh i think",
        "Inevitably, some people will get burned in the process, but others will rise triumphantly from the fray to even greater successes.",
        "I remember the days when there were only a handful of people in the legal offices who spoke Spanish, Dudovitz said. ",
        "get buy-in from stakeholders in the state.",
        "development programs, and pay and promotion standards to organizational mission, vision, and culture.",
        "With so many people packed into such a condensed area, Angelenos are constantly struggling to create unique identities for themselves, which would be more of a challenge if the town didn't have such an  anything goes  attitude.",
        "It was something in the man's eyes.",
        "Typical of his genius was the new religion he offered his  the Divine Faith (Din-Ilahi), intended to satisfy orthodox Muslims and those who, just like himself and the Hindus, appreciated the idea of a semi-divine ruler.",
        "On the corner of Mercaderes and Obispo is the recently renovated, 1920s-era Hotel Ambos Mundos; Hemingway lived on and off in room 511 for a couple of years during the 1930s.",
        "Coptic Christians founded an expansive community for prayer and contemplation here in the fourth century a.d. when many monks chose to live their lives as hermits.",
        "oh yeah the whole i mean the whole thing was done well it was just you know",
        "oh oh yeah well i i i would i mean you know they've got them out here because it's you know they don't actually know what Mexican you know what Mexican food is here",
        "The barrio is one of Madrid's classic working-class areas.",
        "you know it it very much is but on the other hand i realized i could go out on the street and act like a complete lunatic",
    ]

# 2.3
    sentences = [
        "Based on the information presented during public hearings and in comments received on the proposed rule, EPA published a supplemental notice of proposed rulemaking in the Federal Register on March 13, 1995.",
        "yes uh-huh yeah i it's the same way with everything in education though it should begin and right down in the first grade uh and your very best teachers in my estimation should be first second or third grade so that the children develop good learning patterns and have some success and want to go on learning and continue learning uh and not wait until they're in high school and then it's too late to try to change them around at that point",
        "I’m not myself since then. 'What in hell would they need with helicopters?' Hanson asked.(The definition of women here is broad enough to include transvestites and transsexuals.)",
        "all sorts of things that i don't think you know we typically do  we don't take that much time to talk",
        "and budget",
        ". The reason Jews have an injunction against portraying God is that Neanderthals cannot draw.",
        "A number of more recent shopping complexes are set around the Grafton Street area .",
        "Everything was arranged by the family as a penance for avoiding work.",
        "Is it possible, asks Livingstone, that Zapruder was a plant?",
        "(2) What are the effects of these discounts on mailers and on the Nation?",
        " “Interesting material”, he commented, as if only the technical nature of the stuff had offered any problem to him.While I hope many of your readers have had the opportunity to read the e-mail version of Tim's (the student's) article, Lewis is completely wrong about the blackballing.",
        "(Pinker has denied the accusation, arguing that he is trying to understand infanticidal behavior, not condoning it.)",
        "me too if they would oh i know we're saving our grocery bags now",
        "Laryngitis, I said.",
        "When the Republic was proclaimed in Paris in 1848, Schoelcher drafted the emancipation decree that freed 87,500 slaves in Guadeloupe and 72,000 in Martinique.",
        "Since 1996 Legal Aid has increased its annual revenue by $6 million, renovated all of its offices and increased staff salaries Co which helps explain why 7 out of 13 chief (or managing) attorneys around the state are former Legal Aid lawyers who returned after stints in private or government practice.",
        "The Gate Theatre in Parnell Square, has a similar tradition, and stages a cosmopolitan mix of Irish and international theater.",
        "to start like a couple of thousand dollars but there should be a limit over which they that it all goes back to the State anything that they've earned while they're in prison should go back to the State except for that you know there needs to be some allowance for when someone gets out that they have some money to start with",
        "16 According to CBO, that limited time span is insufficient to determine whether the rate of",
        "Jackson, the architecture critic who observed that most American architecture isn't meant to last.",
    ]

# 2.4
    sentences = [
        "yeah yeah they see you go through the problems and still come out okay working together",
        "Yes, yes, he said.",
        "yeah i'm very familiar with the area",
        "no no i don't i just don't have any",
        "i remember at Christmas the the only thing that i'm when you were talking about the composting the only thing that our city did that was they did uh provided a place for us to take our Christmas trees",
        "interactive presentations by security staff to various user groups to market",
        "By adhering to the business case as the key to success, program managers in leading commercial companies are conservative in their estimates and aggressive in risk reduction.",
        "because i mean when you rent a video videos of course are not cheaper either and um and so the idea of getting a little extra with it i think is a good idea because they they make bundles of money off those things",
        " Think nothing splendid, says an old Japanese proverb, until you've seen Nikko. ",
        "Although all dialog and narration are in Japanese, an English interpretation device or an English program is always available.",
        "Similarly, when dictionaries are all online, Random House could hold up the world's Scrabble players and copy editors.",
        "For example, a household could transfer amounts from existing assets to get the government match and then increase consumption in response to its increased wealth.",
        "i don't think so either In fact i think they end up worse because the conditions are so bad",
        "The highlights of the tour are the honours themselves, lying on blue velvet in a secure glass cabinet in the Crown Room.",
        "12Acquiring nonfederal financial assets would reduce the reported unified surplus or increase the unified deficit because, under current budget scoring rules, such acquisitions would be treated as spending.",
        "One of the better swordsmen parried her saber, catching the black steel sword in his own sword's guard only to catch her palm spike in his temple.",
        "And I'll look after YOU, retorted Tuppence, resenting the manly assertion.",
        "We also coordinated with other GAO representatives to identify states that had taken actions to reduce improper payments in federal programs in which program management is a state responsibility, such as the Food Stamp program.",
    ]

# the whole 100 sentences
    sentences = [
        "that's all right",
        "televisions are expensive these days",
        "the colonial porte cochre sets the tone for Waikiki's most charming historic hotel, which opened in 1901",
        "and you just sift",
        "you think there's somethin' in all that talk Topham was givin' lip to? Anse asked",
        "are the uh Oldsmobiles that you're looking at are they the demos or they used are they new",
        "and she's doing it i mean it's not like it's like",
        "ancient and ill-maintained, it starts off shiny and gets rapidly creakier as it approaches the border",
        "one of the first impressions you'll get at the airport in Delhi or Mumbai (Bombay) is the diversity of ethnic types",
        "what about people from uh Pennsylvania what do they think about Texans",
        "b. A lottery ticket that gives you a 10/11 chance of winning $5 million",
        "one is that--contrary to the opinion of virtually everyone else in the world--AIDS in fact hasn't reduced gay males' life expectancy by that much--a few years, at most",
        "he went on and talked about this and that but at dinner repeated exactly the same instructions--I was to run for President, announce the third week in April, etc",
        "'Of course,' Greuze said quickly, 'I wasn't at all implying-'",
        "who better to help a candidate extract weighty lessons from his personal history, to teach him to tell voters that their own successes depend on his own?",
        "mademoiselle Cynthia. ",
        "by time-shifting this feel-good scene forward, Man on the Moon relieves the true story of Kaufman's depressing decline",
        "the coast road takes you west to Pointe du Grouin, a cliff 40 m (130 ft) high, with a spectacular view of the Chausey Islands to the north and to Saint-Malo, a town steeped in seafaring history; its sailors left their name as far afield as the Malouines, claimed by the British as the Falkland Islands",
        "i fully appreciate that much work may be needed before agencies' respective performance management systems are able to support a more direct link between pay and individual knowledge, skills, and performance",
        "a profile of Steve Jurvetson, the 33-year-old venture capitalist who seeds Internet startups, predicts he will prosper even though Internet IPOs no longer promise exponential returns",
        "halfway along the narrow peninsula you'll find Sangster International Airport, the main airport of entry for Kingston and the eastern part of the island",
        "because traditional work schedules influence internal control in T&amp;A systems, this document contains two major parts, the first dealing with civilian employees who are expected to be working, usually during certain times and the second part dealing with members of the active duty armed services who are expected to be in a duty status and thus on call 24 hours a day",
        "but an unfortunate side effect is the lost opportunity to provide some socially desirable planned obsolescence",
        "an article marvels at the revival of religion in China, now used by the Communist Party to control a restive population",
        "this is shown in the supply curve in Figure 9",
        "rudy plans to consolidate his lead in the burbs by pushing school vouchers, while Hillary will tap into health-care frustrations and make the election a national contest",
        "yeah what do they do",
        "the drug can use you",
        "how may a proper person handle the delicate matter of bad breath when happenstance forces one into consulting with someone on the boss' staff?",
        "uh-huh uh-huh uh-huh i know my brother had trouble with fire ants and that even uh yeah and they be can be a real dickens",
        "the Royal Dining Room is situated at the top of the Great Stair",
        "hCFA received 409 comments in the response to the notice",
        "but there's always a sell",
        "so it's a little bit something we try doing and there's there's a lot of good children's programs that you could watch they could watch several hours every day",
        "and that's the great thing, isn't it? ",
        "never did a piece of architecture more exactly express the personality of its builder than the Ceteau de Versailles ' extravagant, pompous, dazzling, formidable, glorious, and vain",
        "oh God  No why don't you go first",
        "without credibility, the CIO organization will struggle to be accepted as a full participant in the development of new organizational systems and processes",
        "some 80 km (50 miles) up the autoroute du Nord from Paris, Com?­piygne is another classical Ile-de-France royal hunting forest and palace",
        "you you have exceeded your ten minutes time limit hang up within the next thirty seconds so",
        "probably the most important reform was the least  the decentralization that increased regional autonomy and reversed the age-old trend of concentrating political, economic, and administrative power in the national capital",
        "they saw their lives lost in that burning town",
        "during the program's critical design review, about 56 percent of the drawings were completed and, while the program did not meet the best practice of 90 percent complete, it did have additional drawing data of the F/A-18 E/F assemblies available for review at the critical design review",
        " The music is played on typically Catalonian and in some cases uniquely Ibicencan  a wooden flute and a small drum (handled simultaneously by a single ambidextrous man), a sort of steel sabre struck in rhythm, and large castanets",
        "what is important is that labor negotiations take place within the framework of a situation where the loss of business to competitors is an everyday reality",
        "well, he showed them",
        "yeah yeah if you like Platoon yeah if you liked Platoon you'll probably really like this because it takes pretty much the same direction for the time you know uh i think",
        "inevitably, some people will get burned in the process, but others will rise triumphantly from the fray to even greater successes",
        "i remember the days when there were only a handful of people in the legal offices who spoke Spanish, Dudovitz said. ",
        "get buy-in from stakeholders in the state",
        "development programs, and pay and promotion standards to organizational mission, vision, and culture",
        "with so many people packed into such a condensed area, Angelenos are constantly struggling to create unique identities for themselves, which would be more of a challenge if the town didn't have such an  anything goes  attitude",
        "it was something in the man's eyes",
        "typical of his genius was the new religion he offered his  the Divine Faith (Din-Ilahi), intended to satisfy orthodox Muslims and those who, just like himself and the Hindus, appreciated the idea of a semi-divine ruler",
        "on the corner of Mercaderes and Obispo is the recently renovated, 1920s-era Hotel Ambos Mundos; Hemingway lived on and off in room 511 for a couple of years during the 1930s",
        "coptic Christians founded an expansive community for prayer and contemplation here in the fourth century a.d. when many monks chose to live their lives as hermits",
        "oh yeah the whole i mean the whole thing was done well it was just you know",
        "oh oh yeah well i i i would i mean you know they've got them out here because it's you know they don't actually know what Mexican you know what Mexican food is here",
        "the barrio is one of Madrid's classic working-class areas",
        "you know it it very much is but on the other hand i realized i could go out on the street and act like a complete lunatic",
        "based on the information presented during public hearings and in comments received on the proposed rule, EPA published a supplemental notice of proposed rulemaking in the Federal Register on March 13, 1995",
        "yes uh-huh yeah i it's the same way with everything in education though it should begin and right down in the first grade uh and your very best teachers in my estimation should be first second or third grade so that the children develop good learning patterns and have some success and want to go on learning and continue learning uh and not wait until they're in high school and then it's too late to try to change them around at that point",
        "i’m not myself since then. 'What in hell would they need with helicopters?' Hanson asked.(The definition of women here is broad enough to include transvestites and transsexuals.)",
        "all sorts of things that i don't think you know we typically do  we don't take that much time to talk",
        "and budget",
        ". The reason Jews have an injunction against portraying God is that Neanderthals cannot draw",
        "a number of more recent shopping complexes are set around the Grafton Street area ",
        "everything was arranged by the family as a penance for avoiding work",
        "is it possible, asks Livingstone, that Zapruder was a plant?",
        "(2) What are the effects of these discounts on mailers and on the Nation?",
        " “Interesting material”, he commented, as if only the technical nature of the stuff had offered any problem to him.While I hope many of your readers have had the opportunity to read the e-mail version of Tim's (the student's) article, Lewis is completely wrong about the blackballing",
        "(Pinker has denied the accusation, arguing that he is trying to understand infanticidal behavior, not condoning it.)",
        "me too if they would oh i know we're saving our grocery bags now",
        "laryngitis, I said",
        "when the Republic was proclaimed in Paris in 1848, Schoelcher drafted the emancipation decree that freed 87,500 slaves in Guadeloupe and 72,000 in Martinique",
        "since 1996 Legal Aid has increased its annual revenue by $6 million, renovated all of its offices and increased staff salaries Co which helps explain why 7 out of 13 chief (or managing) attorneys around the state are former Legal Aid lawyers who returned after stints in private or government practice",
        "the Gate Theatre in Parnell Square, has a similar tradition, and stages a cosmopolitan mix of Irish and international theater",
        "to start like a couple of thousand dollars but there should be a limit over which they that it all goes back to the State anything that they've earned while they're in prison should go back to the State except for that you know there needs to be some allowance for when someone gets out that they have some money to start with",
        "16 According to CBO, that limited time span is insufficient to determine whether the rate of",
        "jackson, the architecture critic who observed that most American architecture isn't meant to last",
        "yeah yeah they see you go through the problems and still come out okay working together",
        "yes, yes, he said",
        "yeah i'm very familiar with the area",
        "no no i don't i just don't have any",
        "i remember at Christmas the the only thing that i'm when you were talking about the composting the only thing that our city did that was they did uh provided a place for us to take our Christmas trees",
        "interactive presentations by security staff to various user groups to market",
        "by adhering to the business case as the key to success, program managers in leading commercial companies are conservative in their estimates and aggressive in risk reduction",
        "because i mean when you rent a video videos of course are not cheaper either and um and so the idea of getting a little extra with it i think is a good idea because they they make bundles of money off those things",
        " Think nothing splendid, says an old Japanese proverb, until you've seen Nikko. ",
        "although all dialog and narration are in Japanese, an English interpretation device or an English program is always available",
        "similarly, when dictionaries are all online, Random House could hold up the world's Scrabble players and copy editors",
        "for example, a household could transfer amounts from existing assets to get the government match and then increase consumption in response to its increased wealth",
        "i don't think so either In fact i think they end up worse because the conditions are so bad",
        "the highlights of the tour are the honours themselves, lying on blue velvet in a secure glass cabinet in the Crown Room",
        "12Acquiring nonfederal financial assets would reduce the reported unified surplus or increase the unified deficit because, under current budget scoring rules, such acquisitions would be treated as spending",
        "one of the better swordsmen parried her saber, catching the black steel sword in his own sword's guard only to catch her palm spike in his temple",
        "and I'll look after YOU, retorted Tuppence, resenting the manly assertion",
        "we also coordinated with other GAO representatives to identify states that had taken actions to reduce improper payments in federal programs in which program management is a state responsibility, such as the Food Stamp program"
    ]


